name: Feature request
description: Propose a feature
labels: [feature]
body:
  - type: textarea
    id: problem
    attributes: {label: Problem}
    validations: {required: true}
  - type: textarea
    id: proposal
    attributes: {label: Proposal}
  - type: textarea
    id: acceptance
    attributes: {label: Acceptance criteria}
